name: Build and Deploy to npm

on:
  release:
    types: [published]

jobs:
  publish-npm-package:
    if: contains(github.event.release.tag_name, 'v0.0.0-latest-master') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install ubuntu deps
        run: sudo apt install mesa-common-dev libglu1-mesa-dev
      - run: npm install
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
